### ISSUE TITLE
Modelar Calificaciones

### ISSUE THREAD

**Issue by lucianobaraglia** [proyectoalba/alba2#2]
## Draft:
- Lo que era escala_nota ahora se llamaría valor_nota, que tiene un tipo, el cual es configurado para ser el utilizado en cada plan de estudios.
- Agreagaría una nueva tabla que sería ConfiguracionPlanEstudio, que resolvería el punto anterior.
- Cambio Nota por Calificación
- Desarrollar una facilidad para las escalas numéricas contínuas, que permita elegir los números extremos y el paso

```
ConfiguracionPlanEstudio:
    id
    tipo_calificacion_id (la escala de notas utilizada para evaluar)
    valor_aprobacion (con cuánto se aprueba al promediar -dejo para futura discusión-)
    ...
    ...

TipoEvaluacion:
    id
    descripcion (TP, Trabajo en Clase, Exámen Escrito, Exámen Oral, Recuperatorio, etc)

Evaluacion (instancia de cada evaluación que se toma):
    id
    tipo_evaluacion_id
    periodo_id
    seccion_id (la sección tiene una referencia al plan de estudio, así que se sabe qué tipo de nota usar)
    docente_id
    asignatura_id
    fecha
    promedia (si/no)

TipoCalificacion:
    id
    descripcion (Escala 1 a 10, Escala 10 a 100, Escala Judeo/Cristiana (¿?))

ValorCalificacion (los valores de cada tipo de escala utilizada):
    id
    tipo_calificacion_id
    descripcion (1, 2, 3, 10, 20, 30, Malo, Regular, Muy Bien!)
    valor_numerico
    orden

Calificacion:
    id
    evaluacion_id
    alumno_id
    valor_calificacion_id
    fecha

```

**Comment by lucianobaraglia** [comment]
Ver https://github.com/proyectoalba/alba2/commit/dbf773b04227f98f3bcf5b8d48babe39eb0e37ff

**Comment by lucianobaraglia** [comment]
El valor de aprobación podría ir en el tipo de calificación.

```
ConfiguracionPlanEstudio:
    id
    plan_estudio_id
    tipo_calificacion_id
    ...

TipoCalificacion:
    id
    descripcion (Escala 1 a 10, Escala 10 a 100, Escala Judeo/Cristiana (¿?))
    valor_aprobación (4, 7)
```

**Comment by lucianobaraglia** [comment]
Se vuelve a cerrar, se da por implementado.

**Comment by OscarZalazar** [comment]
te recuerdo lo que hablamos,.... que hay escuela que tienen examenes con puntuacion en decimal y centesimos por ejemplo: Nota 7.75   y en casos particulares hay puntuaciones con milesimos, el problema es que al hacer el promedio FINAL es necesario que el sistema contabilise y genere la puntuacion final incluyendo los milesimos.

**Comment by lucianobaraglia** [comment]
Gracias por la aclaración!!! :smiley: 
Te cuento que está pensado ese tema.
La idea es que al configurar un plan de estudios se pueda determinar qué tipo de puntaje (escala) utilizar.
El sistema facilitaría las configuraciones más comunes, por ejemplo: "Notas del 1 al 10 con decimales", "Notas del 1 al 100", "No satisfactorio - Satisfactorio", etc etc...
Además se configura el mínimo para considerarlo aprobado.

¿Se entiende?
