### ISSUE TITLE
Acerca de Alumnos, Docentes, Personas...

### ISSUE THREAD

**Issue by lucianobaraglia** [proyectoalba/alba2#22]
En el diseño actual existe la tabla `persona`, que corresponde al perfil o datos personales de un alumno/docente/responsable/quiensea.
O sea, la persona existe como tal una sola vez en el sistema, y a partir de ella puede haber un alumno, también un docente, también un responsable, etc.
Se verifica que la persona no se repita por su tipo y número de documento.

Al crear un alumno por ejemplo queda así:

```
Alumno:
  id: 1
  persona_id: 1

Persona:
  id: 1
  documento: 78456213
  tipo_documento_id: 2
  apellido: Pérez
  nombre: Juan
  ...
  ...
```

Bueno, si bien esto suena bien en la teoría, en la práctica es un poco engorroso de utilizar y quiero simplificarlo.
Alternativas que se me ocurren:
1. Repetir todos los datos personales en cada tabla (`alumno`, `docente`, `responsable`, etc). La contra obvia es que hay datos repetidos, y si por ejemplo creemos que sería bueno incorporar un dato a los perfiles, hay que agregarlo en todas las tablas.
2. Agregar en la tabla `persona` el campo `tipo_persona_id`, que indique si es Alumno, Docente, etc. En este caso el índice único de la tabla sería la combinación de Tipo de Documento, Número de Documento y Tipo de Persona. Es un poco rebuscado pero sería simple que Alumno, Docente, Responsable, etc, hereden de Persona y cada clase tenga su propio tipo. Es fácil de implementar usando polimorfismo.

**Comment by hectorsanchez** [comment]
La opción 2 me gusta más, pero que pasa si una persona es docente y alumno? esto puede pasar, en este caso la opción 2 ya no sirve.

La opción 1, hace repetir datos lo que tiene de costoso es espacio, que es barato.. a mi no me molestaría repetir esos campos.

**Comment by lucianobaraglia** [comment]
A mí también me gusta la opción 2, es más limpia aunque más rebuscada.
Y una persona puede ser Docente y Alumno al mismo tiempo, ya que el índice único es por el Tipo Documento, Número de Documento y Tipo de Persona.

**Comment by hectorsanchez** [comment]
Si es verdad, entonces mi +1 a las opción 2.

**Comment by ftoledo** [comment]
la herencia nunca me gustó como se persiste de esta forma
por ejemplo la 1 es la que usaba symfony (doctrine) que si repetís campos para eso ahorrate la tabla principal que pierde sentido practico desde mi unto de vista.
y la 2 produce que se terminen harcodeando cosas a nivel logica
por ejemplo la busqueda de alumnos vas a tener que filtrar por el tipo 1 en la de docentes por 2 etc..
es como que siempre vas a tener que hardcodear el tipo de dato.
inclusive cuando  obtenés datos, vas a tener que hacer un case segun el tipo para ver que campos traes!
 el ultimo caso es cuando das de alta que tenes que crear un registro en persona, luego en docente o alumno con el id de persona creado (todo en una transaccion)

desde mi punto de vista por mas que un alumno y un docente sean una persona
a veces prefiero que no tengan una relacion de herencia.
porque de ultima si quiero buscar por todas las personas, ahi si busco en la dos tablas y es un solo lugar que hago este medio feo
en vez de tener que estar haciendo cosas feas en cada lugar que se usen las personas.

quizas @miguelgarcia tenga una idea mejor de modelado
=(

aca esta en modelado como lo harias en 2:
http://www.miguelmatas.es/blog/blog/2008/01/19/%C2%BFherencia-en-bbdd/

**Comment by miguelgarcia** [comment]
Yo usaria herencia, si el ORM de Yii la maneja bien.

Alumno y Docente heredarian de Persona, de esa forma si tenes que agregar más info a todas las personas solo tocas la clase Persona. Terminarias con algo como la solución 1.

Hay que ver para este caso que tan probable es que un alumno sea docente y cuantos datos realmente tiene sentido compartir, es raro que te interesen los mismos datos para los distintos tipos de persona. Yo, teniendo en cuenta las particularidades de las escuelas iria por entidades separadas e independientes.

**Comment by lucianobaraglia** [comment]
@ftoledo te entiendo.
Igual pienso que es mucho menos costoso harcodear el tipo de dato que tener 3 o 4 clases/tablas similares con una funcionalidad similar.
@miguelgarcia, YII por ahora no soporta la herencia de tablas nativamente, pero como yo me la imagino es algo así:

``` php
class Persona extends yii\db\ActiveRecord 
{
    protected $_tipo_persona;
    //
    const TIPO_ALUMNO = 1;
    const TIPO_DOCENTE = 2;
    const TIPO_RESPONSABLE = 3;
    // declaración de la clase, blah blah
    ...
    ...
    ...

    // sobreescribo el beforeSave al crear el objeto:
    public function beforeSave($insert)
    {
        if($insert){
            $this->tipo_persona_id = $this->_tipo_persona;
        }
    }
    // podría sobreescribir el `find` o algo así también, es sólo un ejemplo
    public function find()
    {
        return Persona::find()->where(['tipo_persona_id' => $this->_tipo_persona]);
    }
}
//
//
class Alumno extends Persona {
    protected $_tipo_persona = Persona::TIPO_ALUMNO;
}

//
class Responsable extends Persona {
    protected $_tipo_persona = Persona::TIPO_RESPONSABLE;
}

//
class Docente extends Persona {
    protected $_tipo_persona = Persona::TIPO_DOCENTE;
}
//
```

Lo bueno de tener los datos de los n tipos de personas del sistema, es que YII tiene lo que se llama `scenarios`, que permite por ejemplo tener diferentes validaciones o comportamientos dependiendo del `scenario`.
Un `scenario` podría ser `alumno`, otro `docente` y así.

Y sí, siempre va a haber que tocar el código cuando hay un cambio. El tema es si hacerlo en 4 lados o sólo en 1.

Por ahí es un poco confuso el término `Persona`, pero realmente lo que guarda son los datos personales del usuario. Así que el concepto podría aplicarse a algo como `Perfil`.
Yo lo que quiero evitar principalmente es tener 4 clases con 20 campos similares.
Si a esa clase la llamamos `Persona` y las restantes heredan o la llamamos `Perfil` y las clases restantes usan composición, me da igual.

¿Qué opinan?

**Comment by miguelgarcia** [comment]
Todos los alumnos y docentes van a tener un usuario ?

**Comment by lucianobaraglia** [comment]
Hace mucho hablando con @ftoledo, él decía que tanto a responsables, como a alumnos y docentes, habría que meterles un password para que sean automaticamente usuarios...
Es una opción, pero no tenemos definido eso...
¿Cuál es tu idea?

**Comment by miguelgarcia** [comment]
Yo lo haria opcional, que alumno, docente y responsable tengan una relacion opcional a usuario. Pero no lo forzaria, no mezclaria el modelo del negocio en si con el manejo de usuarios.

**Comment by lucianobaraglia** [comment]
Suena lógico...
De última si lo piden (¿?), en algún momento se puede crear un proceso que genera "Usuarios para todos"...

Volviendo al tema de este ticket, ¿cómo avanzamos?
¿Probamos con herencia (heredan de Persona como en mi ejemplo) o composición (tienen una relación a Perfil)?

**Comment by miguelgarcia** [comment]
Sigo sin entender :P El perfil es el usuario ? Que atributos tiene perfil ?

**Comment by lucianobaraglia** [comment]
Me cache en Die... :neutral_face: 
El `Perfil` hasta ahora no existe, me refiero a los datos personales de la persona. Pensá en `Perfil` como traducción de `Profile`...

Lo que digo es que tanto alumnos, docentes y responsables apunten a una tabla llamada `Perfil`, que tenga los datos personales.
De última, pensar si vale realmente el esfuerzo de poder reutilizar los datos si la misma persona es alumno y responsable (¿qué chances?) o si vuelven a cargar los datos y listo.

ssssentiende?

**Comment by miguelgarcia** [comment]
Ahh entonces seria como una clase Person ? Si es asi para mi no tiene sentido, reutilizas muy pocos datos y se hace mas complejo el manejo del modelo. Si re usar los responsables, si tiene 2 alumnos no cargarlo 2 veces, que sea realmente el mismo objeto Responsable.

**Comment by lucianobaraglia** [comment]
Ok...entonces simplemente que haya una tabla `Perfil`, ponéle, y que ahí se carguen los datos personales de todos los otros modelos.
De esta forma tenemos en esa tabla datos comunes: `tipo_documento_id`, `numero_documento`, `fecha_nacimiento`, etc, etc...
Y tanto `Alumno`, `Responsable` y `Docente` tienen una columna `perfil_id`...

¿Así te parece?

**Comment by miguelgarcia** [comment]
Yo decia sin tabla Perfil, direto que alumno tenga sus campos, docente sus campos, etc

**Comment by lucianobaraglia** [comment]
Es lo que quiero evitar desde el principio, hacer una tabla de perfiles es lo más básico que podemos apuntar para no tener tablas tan similares.

**Comment by lucianobaraglia** [comment]
Implementado en los últimos cambios...
